config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :users, only: [:new, :create, :show]
  resource :session, only: [:new, :create, :destroy]

  resources :bands do
    resources :albums, only: [:new]
  end

  resources :albums, only: [:create, :edit, :show, :update, :destroy] do
    resources :tracks, only: [:new]
  end

  resources :tracks, only: [:create, :edit, :show, :update, :destroy]
end

app/models/album.rb
# == Schema Information
#
# Table name: albums
#
#  id      :bigint(8)        not null, primary key
#  band_id :integer          not null
#  title   :string           not null
#  year    :integer          not null
#  studio  :boolean          default(TRUE)
#

class Album < ApplicationRecord
  validates :band_id, :title, :year, presence: true

  belongs_to :band,
  primary_key: :id,
  foreign_key: :band_id,
  class_name: :Band

  has_many :tracks,
  primary_key: :id,
  foreign_key: :album_id,
  class_name: :Track,
  dependent: :destroy
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/band.rb
# == Schema Information
#
# Table name: bands
#
#  id         :bigint(8)        not null, primary key
#  name       :string           not null
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Band < ApplicationRecord
  validates :name, presence: true

  has_many :albums,
  primary_key: :id,
  foreign_key: :band_id,
  class_name: :Album

end

app/models/track.rb
# == Schema Information
#
# Table name: tracks
#
#  id       :bigint(8)        not null, primary key
#  album_id :integer          not null
#  title    :string           not null
#  ord      :integer          not null
#  lyrics   :text
#  bonus    :boolean          default(FALSE)
#

class Track < ApplicationRecord

  validates :title, :ord, :album_id, presence: true

  belongs_to :album,
  primary_key: :id,
  foreign_key: :album_id,
  class_name: :Album
end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id              :bigint(8)        not null, primary key
#  email           :string           not null
#  password_digest :string           not null
#  session_token   :string           not null
#  created_at      :datetime         not null
#  updated_at      :datetime         not null
#

class User < ApplicationRecord
  attr_reader :password
  before_validation :ensure_session_token
  validates :email, :session_token, presence: true, uniqueness: true
  validates :password_digest, presence: true
  validates :password, length: { minimum: 6, allow_nil: true }

  def self.find_by_credentials(email, password)
    user = User.find_by(email: email)
    return nil if user == nil
    user.is_password?(password) ? user : nil
  end

  def ensure_session_token
    self.session_token ||= SecureRandom::urlsafe_base64
  end

  def password=(password)
    @password = password
    self.password_digest = BCrypt::Password.create(password)
  end

  def is_password?(password)
    BCrypt::Password.new(self.password_digest).is_password?(password)
  end

  def reset_session_token!
    self.session_token = SecureRandom::urlsafe_base64
    self.save!
    self.session_token
  end


end

app/controllers/albums_controller.rb
class AlbumsController < ApplicationController

  before_action :require_logged_in
  def new
    @album = Album.new
    render :new
  end

  def create
    @album = Album.new(album_params)
    if @album.save
      redirect_to band_url(@album.band_id)
    else
      flash[:errors] = @album.errors.full_messages
      render :new
    end
  end

  def show
    @album = Album.find(params[:id])
    render :show
  end

  def edit
    @album = Album.find(params[:id])
    render :edit
  end

  def update
    @album = Album.find(params[:id])
    if @album.update_attributes(album_params)
      redirect_to band_url(@album.band_id)
    else
      flash[:errors] = @band.errors.full_messages
      render :edit
    end
  end

  def destroy
    @album.find(params[:id])
    id = @album.band_id
    @album.destroy
    redirect_to band_url(id)
  end

  private
  def album_params
    params.require(:album).permit(:band_id, :title, :year, :studio)
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  helper_method :current_user, :logged_in?

  def current_user
    return nil if session[:session_token] == nil
    @current_user ||= User.find_by(session_token: session[:session_token])
  end

  def login_user!(user)
    @current_user = user
    session[:session_token] = user.reset_session_token!
  end

  def logout_user!
    current_user.reset_session_token!
    session[:session_token] = nil
  end

  def logged_in?
    !!current_user
  end

  def logged_out?
    !current_user
  end


  def require_logged_in
    redirect_to new_session_url unless current_user
  end
end

app/controllers/bands_controller.rb
class BandsController < ApplicationController

  before_action :require_logged_in
  def index
    @bands = Band.all
    render :index
  end

  def new
    @band = Band.new
    render :new
  end

  def create
    @band = Band.new(band_params)

    if @band.save
      redirect_to bands_url
    else
      flash[:errors] = @band.errors.full_messages
      render :new
    end
  end

  def show
    @band = Band.find(params[:id])
    render :show
  end

  def edit
    @band = Band.find(params[:id])
    render :edit
  end

  def update
    @band = Band.find(params[:id])
    if @band.update_attributes(band_params)
      redirect_to band_url(@band)
    else
      flash[:errors] = @band.errors.full_messages
      render :edit
    end
  end

  def destroy
    @band = Band.find(params[:id])
    @band.destroy
    redirect_to bands_url
  end


  private
  def band_params
    params.require(:band).permit(:name)
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
    render :new
  end

  def create
    @user = User.find_by_credentials(params[:user][:email], params[:user][:password])
    if @user
      login_user!(@user)
      redirect_to bands_url
    else
      flash[:errors] = @user.errors.full_messages
      render :new
    end
  end

  def destroy
    logout_user!
    redirect_to new_session_url
  end

end

app/controllers/tracks_controller.rb
class TracksController < ApplicationController

  before_action :require_logged_in
  def new
    @track = Track.new
    render :new
  end

  def create
    @track = Track.new(track_params)
    if @track.save
      redirect_to album_url(@track.album_id)
    else
      flash[:errors] = @track.errors.full_messages
      render :new
    end
  end

  def show
    @track = Track.find(params[:id])
    render :show
  end

  def edit
    @track = Track.find(params[:id])
    render :edit
  end

  def update
    @track = Track.find(params[:id])
    if @track.update_attributes(track_params)
      redirect_to album_url(@track.album_id)
    else
      flash[:errors] = @track.errors.full_messages
      render :edit
    end
  end

  def destroy
    @track.find(params[:id])
    id = @track.album_id
    @track.destroy
    redirect_to album_url(id)
  end

  private
  def track_params
    params.require(:track).permit(:album_id, :title, :ord, :lyrics, :bonus)
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def new
    @user = User.new
    render :new
  end

  def create
    @user = User.new(user_params)

    if @user.save
      login_user!(@user)
      redirect_to bands_url
    else
      flash.now[:errors] = @user.errors.full_messages
      render :new

    end
  end

  def show
    @user = User.find(params[:id])
    if @user
      render :show
    else
      redirect_to new_session_url
    end
  end

  private
  def user_params
    params.require(:user).permit(:email, :password)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def auth_token
    html = "<input type='hidden' name='authenticity_token' value='#{form_authenticity_token}'/>".html_safe
  end
end

app/views/albums/_form.html.erb
<% if type == :new %>
  <% action_url = albums_url %>
  <% button_text = "Create New Album" %>
<% elsif type == :edit %>
  <% action_url = album_url(album) %>
  <% button_text = "Edit Album" %>
<% end %>
<form action="<%= action_url %>" method="post">
  <%=auth_token%>
  <% if type == :edit %>
    <input type="hidden" name="_method" value="patch">
  <% end %>
  <label for="album-artist">Artist</label>
    <select name="album[band_id]" id="album-artist">
      <option></option>
      <% Band.all.each do |band| %>
        <% selected = album.band_id == band.id %>
        <option <%= selected ? "selected" : "" %> value="<%=band.id%>">
          <%= band.name %>
        </option>
      <% end %>
    </select>
    <br>
    <br>
  <label for="album-name">Album Title:</label>
    <input type id="album-name" type="text" name="album[title]" value="<%=album.title%>">
  <br>
  <br>
  <label for="album-year">Year:</label>
    <input type id="album-year" type="text" name="album[year]" value="<%=album.year%>">
  <br>
  <br>
  <input type="radio" name="album[studio]" value="true" id="studio-album"
    <%= album.studio == true ? "checked" : "" %>>
  <label for="studio-album">Studio Album</label>
  <input type="radio" name="album[studio]" value="false" id="live-album"
    <%= album.studio == false ? "checked" : "" %>>
  <label for="live-album">Live Album</label>
  <br>
  <br>
  <input type="submit" value="<%=button_text%>">
</form>

app/views/albums/edit.html.erb
<h2 class="page-header">Edit Album</h2>
<%= render 'form', album: @album, type: :edit %>

app/views/albums/new.html.erb
<h2 class="page-header">New Album</h2>
<%= render 'form', album: @album, type: :new %>

app/views/albums/show.html.erb
<h2 class = "page-header"><%=@album.title%><h2>
  <ul>
    <li>BY: <%= Band.find(@album.band_id).name %></li>
    <li><%= @album.year %></li>
    <% if @album.studio %>
    <li>Studio Album</li>
    <% else %>
    <li>Live Album</li>
    <% end %>
  <ul>
<br>

<ul class="main-list">
  <% @album.tracks.each do |track| %>
    <li><a href= "<%=track_url(track)%>">
      <p><%= track.title %></p></a>
    </li>
  <%end%>
</ul>

<ul class="page-links">
  <li>
    <a class="button" href="<%=new_album_track_url(@album)%>">Create New Track</a>
  </li>

  <li>
    <a class = "button" href="<%=edit_album_url(@album)%>">Edit Album</a>
  </li>
  <li>
  <form action="<%=album_url(@album)%>" method="post">
    <input type="hidden" name="_method" value="DELETE">
    <%= auth_token %>
    <input type="submit" value="Destroy album">
  </form>
  </li>
<ul>

app/views/bands/edit.html.erb
<h2 class="page-header">Edit <%=@band.name%><h2>
<form action="<%=band_url(@band)%>" method="post">
  <input type="hidden" name="_method" value="patch">
  <%=auth_token%>
  <label for="band-name">Band Name:</label>
    <input type id="band-name" type="text" name="band[name]" value="<%=@band.name%>">
  <input type="submit" value="Edit band">

</form>

app/views/bands/index.html.erb
<h2 class="page-header">Bands</h2>

<ul class="main-list">
  <% @bands.each do |band| %>
    <li><a href= "<%=band_url(band)%>">
      <p><%= band.name %></p></a>
    </li>
  <%end%>
</ul>

<a href="<%= new_band_url %>">Create New Band</a>

app/views/bands/new.html.erb
<h2 class="page-header">New Band!<h2>
<form action="<%=bands_url%>" method="post">
  <%=auth_token%>
  <label for="band-name">Band Name:</label>
    <input type id="band-name" type="text" name="band[name]">
  <input type="submit" value="Create new band">

</form>

app/views/bands/show.html.erb
<h2 class ="page-header"><%= @band.name %></h2>

<ul class="main-list">
  <% @band.albums.each do |album| %>
    <li><a href= "<%=album_url(album)%>">
      <p><%= album.title %></p></a>
    </li>
  <%end%>
</ul>

<ul class="page-links">
  <li>
    <a class="button" href="<%=new_band_album_url(@band)%>">Create New Album</a>
  </li>
  <li>
    <a class="button"href="<%=edit_band_url(@band)%>">Edit Band</a>
  </li>
  <li>
    <form action="<%=band_url(@band)%>" method="post">
      <input type="hidden" name="_method" value="DELETE">
      <%= auth_token %>
      <input type="submit" value="Destroy band">
    </form>
  </li>
  <li>
    <a class="button" href="<%= new_band_url %>">Create New Band</a>
  </li>


</ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MusicApp</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
  </head>

  <body>
      <% if flash[:notice] %>
        <p><%= flash[:notice] %></p>
      <% end %>

      <% if flash[:errors] %>
        <p><%= flash[:errors].join(", ") %></p>
      <% end %>
    <div class="main-content">
      <h1 class="main-logo">Music App</h1>
      <% if logged_in? %>
        <nav>
          <a class="button" href= "<%=bands_url%>">All Bands</a>
          <div>
            <p>Logged in as: <%=current_user.email=%></p>
            <form action="<%=session_url%>" method="post">
              <%=auth_token%>
              <input type="hidden" name="_method" value="delete">
              <input type="submit" value="Sign Out">
            </form>
          </div>
        </nav>
      <% else %>
        <nav>
          <a class="button" href="<%= new_session_url %>">Sign In</a>
          <a class="button" href="<%= new_user_url %>">Signup</a>
        </nav>
      <% end %>
      <%= yield %>
    </div>
  </body>
</html>

app/views/tracks/_form.html.erb
<% if type == :new %>
  <% action_url = tracks_url %>
  <% button_text = "Create New Track" %>
<% else %>
  <% action_url = track_url(track) %>
  <% button_text = "Edit Track" %>
<% end %>
<form action="<%= action_url %>" method="post">
  <%=auth_token%>
  <% if type == :edit %>
    <input type="hidden" name="_method" value="patch">
  <% end %>
  <label for="track-album">Album</label>
    <select name="track[album_id]" id="track-album">
      <option></option>
      <% Album.all.each do |album| %>
        <% selected = track.album_id == album.id %>
        <option <%= selected ? "selected" : "" %> value="<%=album.id%>">
          <%= album.title %>
        </option>
      <% end %>
    </select>
    <br>
    <br>
  <label for="track-name">Track Title:</label>
    <input type id="track-name" type="text" name="track[title]" value="<%=track.title%>">
  <br>
  <br>
  <label for="track-ord">Order</label>
    <input type id="track-ord" type="text" name="track[ord]" value="<%=track.ord%>">
  <br>
  <br>
  <input type="radio" name="track[bonus]" value="true" id="bonus-track"
    <%= track.bonus == true ? "checked" : "" %>>
  <label for="bonus-track">Bonus Track</label>
  <input type="radio" name="track[bonus]" value="false" id="reg-track"
    <%= track.bonus == false ? "checked" : "" %>>
  <label for="bonus-track">Regular Track</label>
  <br>
  <br>
  <label>
    Lyrics
    <textarea name="track[lyrics]"><%= track.lyrics %></textarea>
  </label>
  <br>
  <br>
  <input type="submit" value="<%=button_text%>">
</form>

app/views/tracks/edit.html.erb
<h2 class="page-header">Edit Track</h2>
<%= render 'form', track: @track, type: :edit %>

app/views/tracks/new.html.erb
<h2 class="page-header">New Track</h2>
<%= render 'form', track: @track, type: :new %>

app/views/tracks/show.html.erb
<h2 class = "page-header"><%=@track.title%><h2>
<ul>
  <li>Album: <%= Album.find(@track.album_id).title %></li>
  <li>Order: <%= @track.ord %></li>
  <% if @track.bonus %>
  <li>Bonus Track</li>
  <% else %>
  <li>Regular Track</li>
  <% end %>
  <li>Lyrics:
    <p><%= @track.lyrics %></p>
  </li>
</ul>

  <ul class="page-links">

    <li>
      <a class = "button" href="<%=edit_track_url(@track)%>">Edit Track</a>
    </li>
    <li>
    <form action="<%=track_url(@track)%>" method="post">
      <input type="hidden" name="_method" value="DELETE">
      <%= auth_token %>
      <input type="submit" value="Destroy track">
    </form>
    </li>
  </ul>

app/views/users/_form.html.erb
<% if type == :new %>
  <% action_url = users_url %>
  <% button_text = "Create User" %>
    <h2 class="page-header">New user</h2>

<% else %>
  <% action_url = session_url %>
  <% button_text = "Submit"%>
    <h2 class="page-header">Sign In</h2>

<% end %>
<form action="<%=action_url%>" method="post">
  <%=auth_token%>
  <p>
    <label for="user-email">Email</label>
    <input id ="user-email" type="text" name="user[email]">
  </p>
  <p>
    <label for="user-password">password</label>
    <input id ="user-password" type="password" name="user[password]">
  </p>
  <input type="submit" value="<%=button_text%>">
</form>

app/views/users/new.html.erb
<%= render 'form', type: :new %>